# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54a94677fa8ce2c44871440ac58e8f3e6de0d567c4130d70373064ead4363113deedc2b112a3b93724bfd1604a3e0b19d0ea4f9620cc868ad6f91b26e827fd63

test:
  secret_key_base: 85da18b8f19cbf788b3f455851d39615caa3f12c005593aaa061d2abc8abcfacd8440c59700ad5522d7ed46ed6e543f2c916cbf8f8c3cb80a92f74e25d10be02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
